"use client";

import { useEffect, useState } from "react";

const DISMISSED_KEY = "firstoffer_push_dismissed";

// Converts the VAPID public key (base64url, as generated by
// `web-push generate-vapid-keys`) into the Uint8Array PushManager.subscribe
// requires — standard boilerplate for the Push API, not FirstOffer-specific.
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; i += 1) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

// Opt-in banner for "new opportunities added — go fast and apply" push
// notifications. No sign-in required, matching the rest of the site. Lives
// in app/layout.tsx so it can show on any page, but only actually renders
// its UI when there's something to ask (browser supports Push, permission
// hasn't been decided yet, and the visitor hasn't dismissed it before) —
// otherwise it silently no-ops or silently re-subscribes in the background.
export default function PushNotificationPrompt() {
  const [visible, setVisible] = useState(false);
  const [isSubscribing, setIsSubscribing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
    if (!publicKey) return;
    if (!("serviceWorker" in navigator) || !("PushManager" in window)) return;
    if (typeof Notification === "undefined") return;

    let cancelled = false;

    async function init(key: string) {
      try {
        const registration = await navigator.serviceWorker.register("/sw.js");

        if (Notification.permission === "denied") return;

        const existing = await registration.pushManager.getSubscription();
        if (existing) return; // already subscribed, nothing to do

        if (Notification.permission === "granted") {
          // Permission was granted before but the subscription is gone
          // (e.g. site data cleared) — re-subscribe quietly, no banner.
          await subscribe(registration, key);
          return;
        }

        const dismissed = window.localStorage.getItem(DISMISSED_KEY);
        if (!dismissed && !cancelled) {
          setVisible(true);
        }
      } catch {
        // Service worker registration can fail (unsupported browser,
        // blocked by an extension, etc.) — fail silent, this is a nice-to
        // -have feature, never something worth surfacing as an error.
      }
    }

    init(publicKey);
    return () => {
      cancelled = true;
    };
  }, []);

  async function subscribe(registration: ServiceWorkerRegistration, publicKey: string) {
    const subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(publicKey) as BufferSource,
    });

    await fetch("/api/push/subscribe", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(subscription.toJSON()),
    });
  }

  async function handleEnable() {
    const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
    if (!publicKey) return;

    setIsSubscribing(true);
    setError(null);
    try {
      const permission = await Notification.requestPermission();
      if (permission !== "granted") {
        setVisible(false);
        window.localStorage.setItem(DISMISSED_KEY, "1");
        return;
      }
      const registration = await navigator.serviceWorker.ready;
      await subscribe(registration, publicKey);
      setVisible(false);
    } catch {
      setError("Couldn't enable notifications — please try again.");
    } finally {
      setIsSubscribing(false);
    }
  }

  function handleDismiss() {
    setVisible(false);
    window.localStorage.setItem(DISMISSED_KEY, "1");
  }

  if (!visible) return null;

  return (
    <div className="push-prompt" role="dialog" aria-label="Enable notifications">
      <span className="push-prompt-icon" aria-hidden="true">🔔</span>
      <div className="push-prompt-body">
        <p className="push-prompt-title">Never miss a fresh opportunity</p>
        <p className="push-prompt-desc">
          Get notified the instant new fresher jobs go live on FirstOffer — go fast and apply before they&apos;re
          gone.
        </p>
        {error && <p className="push-prompt-error">{error}</p>}
      </div>
      <div className="push-prompt-actions">
        <button type="button" className="btn btn-secondary btn-sm" onClick={handleDismiss} disabled={isSubscribing}>
          Not now
        </button>
        <button type="button" className="btn btn-primary btn-sm" onClick={handleEnable} disabled={isSubscribing}>
          {isSubscribing ? "Enabling..." : "Enable notifications"}
        </button>
      </div>
    </div>
  );
}
